[package]
name = "printer"
version = "0.1.0"
edition = "2021"

[dependencies]
ev3dev-lang-rust = { version="0.15.0" }

[build]
target = "armv5te-unknown-linux-musleabi"

[target.armv5te-unknown-linux-musleabi]
linker = "rust--lld"
